<?php

/**
 * This class has been auto-generated by the IPF_ORM Framework.
 * Changes to this file may cause incorrect behavior
 * and will be lost if the code is regenerated.
 */

abstract class BaseSession extends IPF_ORM_Record
{
  public function setTableDefinition()
  {
    $table = $this->getTable();
    $table->setTableName('session');
    $this->getTable()->setColumn('session_key', 'string', 40, array('primary' => true, 'type' => 'string', 'length' => '40'));
    $this->getTable()->setColumn('session_data', 'string', null, array('type' => 'string'));
    $this->getTable()->setColumn('expire_data', 'timestamp', null, array('type' => 'timestamp'));
  }



  public static function table()
  {
    return IPF_ORM::getTable('Session');
  }

  public static function query($alias='')
  {
    return IPF_ORM::getTable('Session')->createQuery($alias);
  }
}