<?php

/**
 * This class has been auto-generated by the IPF_ORM Framework
 */
abstract class BaseSession extends IPF_ORM_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('session');
    $this->hasColumn('session_key', 'string', 40, array('primary' => true, 'type' => 'string', 'length' => '40'));
    $this->hasColumn('session_data', 'string', null, array('type' => 'string'));
    $this->hasColumn('expire_data', 'timestamp', null, array('type' => 'timestamp'));
  }

}