<?php

/**
 * This class has been auto-generated by the IPF_ORM Framework.
 * Changes to this file may cause incorrect behavior
 * and will be lost if the code is regenerated.
 */

abstract class BaseUserRole extends IPF_ORM_Record
{
  public static function setTableDefinition(IPF_ORM_Table $table)
  {
    $table->setTableName('auth_user_role');
    $table->setColumn('user_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $table->setColumn('role_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $table->setOption('type', 'INNODB');
    $table->setOption('collate', 'utf8_unicode_ci');
    $table->setOption('charset', 'utf8');

  }

  public static function setUp(IPF_ORM_Table $table)
  {
    $table->hasOne('User', '', array('local' => 'user_id', 'foreign' => 'id', 'onDelete' => 'CASCADE'));
    $table->hasOne('Role', '', array('local' => 'role_id', 'foreign' => 'id', 'onDelete' => 'CASCADE'));
  }

  public static function table()
  {
    return IPF_ORM::getTable('UserRole');
  }

  public static function query($alias='')
  {
    return IPF_ORM::getTable('UserRole')->createQuery($alias);
  }
}