<?php

/**
 * This class has been auto-generated by the IPF_ORM Framework
 */
abstract class BaseUserRole extends IPF_ORM_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('auth_user_role');
    $this->hasColumn('user_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('role_id', 'integer', null, array('type' => 'integer', 'primary' => true));

    $this->option('type', 'INNODB');
    $this->option('collate', 'utf8_unicode_ci');
    $this->option('charset', 'utf8');
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'user_id',
                                'foreign' => 'id'));

    $this->hasOne('Role', array('local' => 'role_id',
                                'foreign' => 'id'));
  }
}