<?php

/**
 * This class has been auto-generated by the IPF_ORM Framework
 */
abstract class BaseRolePermission extends IPF_ORM_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('auth_role_permission');
    $this->hasColumn('role_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('permission_id', 'integer', null, array('type' => 'integer', 'primary' => true));

    $this->option('type', 'INNODB');
    $this->option('collate', 'utf8_unicode_ci');
    $this->option('charset', 'utf8');
  }

  public function setUp()
  {
    $this->hasOne('Role', array('local' => 'role_id',
                                'foreign' => 'id',
                                'onDelete' => 'CASCADE'));

    $this->hasOne('Permission', array('local' => 'permission_id',
                                      'foreign' => 'id',
                                      'onDelete' => 'CASCADE'));
  }
}
