<?php

/**
 * This class has been auto-generated by the IPF_ORM Framework.
 * Changes to this file may cause incorrect behavior
 * and will be lost if the code is regenerated.
 */

abstract class BaseRole extends IPF_ORM_Record
{
  public static function setTableDefinition(IPF_ORM_Table $table)
  {
    $table->setTableName('auth_role');
    $table->setColumn('name', 'string', 255, array('unique' => true, 'type' => 'string', 'notblank' => true, 'length' => '255'));
    $table->setOption('type', 'INNODB');
    $table->setOption('collate', 'utf8_unicode_ci');
    $table->setOption('charset', 'utf8');

  }

  public static function setUp(IPF_ORM_Table $table)
  {
    $table->hasMany('Permission', 'Permissions', array('refClass' => 'RolePermission', 'local' => 'role_id', 'foreign' => 'permission_id'));
    $table->hasMany('User', 'Users', array('refClass' => 'UserRole', 'local' => 'role_id', 'foreign' => 'user_id'));
    $table->hasMany('RolePermission', '', array('local' => 'id', 'foreign' => 'role_id'));
    $table->hasMany('UserRole', '', array('local' => 'id', 'foreign' => 'role_id'));
  }

  public static function table()
  {
    return IPF_ORM::getTable('Role');
  }

  public static function query($alias='')
  {
    return IPF_ORM::getTable('Role')->createQuery($alias);
  }
}