<?php

/**
 * This class has been auto-generated by the IPF ORM Framework
 */
abstract class BaseUserPermission extends IPF_ORM_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('auth_user_permission');
    $this->hasColumn('user_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('permission_id', 'integer', null, array('type' => 'integer', 'primary' => true));

    $this->option('type', 'INNODB');
    $this->option('collate', 'utf8_unicode_ci');
    $this->option('charset', 'utf8');
  }

  public function setUp()
  {
    $this->hasOne('User', array('local' => 'user_id',
                                'foreign' => 'id'));

    $this->hasOne('Permission', array('local' => 'permission_id',
                                      'foreign' => 'id'));
  }
}