<?php

/**
 * This class has been auto-generated by the IPF_ORM Framework.
 * Changes to this file may cause incorrect behavior
 * and will be lost if the code is regenerated.
 */

abstract class BasePermission extends IPF_ORM_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('auth_permission');
    $this->getTable()->setColumn('name', 'string', 255, array('unique' => true, 'type' => 'string', 'length' => '255'));
    $this->option('type', 'INNODB');
    $this->option('collate', 'utf8_unicode_ci');
    $this->option('charset', 'utf8');

  }

  public function setUp()
  {
    $this->hasMany('User as Users', array('refClass' => 'UserPermission',
                                          'local' => 'permission_id',
                                          'foreign' => 'user_id'));

    $this->hasMany('Role as Roles', array('refClass' => 'RolePermission',
                                          'local' => 'permission_id',
                                          'foreign' => 'role_id'));

    $this->hasMany('RolePermission', array('local' => 'id',
                                           'foreign' => 'permission_id'));

    $this->hasMany('UserPermission', array('local' => 'id',
                                           'foreign' => 'permission_id'));
  }

  public static function table()
  {
    return IPF_ORM::getTable('Permission');
  }

  public static function query($alias='')
  {
    return IPF_ORM::getTable('Permission')->createQuery($alias);
  }
}