<?php

/**
 * This class has been auto-generated by the IPF_ORM Framework.
 * Changes to this file may cause incorrect behavior
 * and will be lost if the code is regenerated.
 */

abstract class BaseAdminLog extends IPF_ORM_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('admin_log');
    $this->hasColumn('username', 'string', 32, array('type' => 'string', 'length' => '32'));
    $this->hasColumn('user_id', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('object_id', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('object_class', 'string', 200, array('type' => 'string', 'length' => '200'));
    $this->hasColumn('object_repr', 'string', 200, array('type' => 'string', 'length' => '200'));
    $this->hasColumn('action_flag', 'integer', null, array('type' => 'integer'));
    $this->hasColumn('change_message', 'string', 200, array('type' => 'string', 'length' => '200'));
    $this->index('idx_object_id', array('fields' => 'object_id'));
    $this->index('idx_object_class', array('fields' => 'object_class'));
    $this->index('idx_created_at', array('fields' => 'created_at'));
    $this->index('idx_action_flag', array('fields' => 'action_flag'));
    $this->option('type', 'INNODB');
    $this->option('collate', 'utf8_unicode_ci');
    $this->option('charset', 'utf8');

  }

  public function setUp()
  {
    $timestampable0 = new IPF_ORM_Template_Timestampable(array('updated' => array('disabled' => true)));
    $this->getTable()->addTemplate($timestampable0);
  }

  public static function table()
  {
    return IPF_ORM::getTable('AdminLog');
  }

  public static function query($alias='')
  {
    return IPF_ORM::getTable('AdminLog')->createQuery($alias);
  }
}