<?php

/**
 * This class has been auto-generated by the IPF_ORM Framework.
 * Changes to this file may cause incorrect behavior
 * and will be lost if the code is regenerated.
 */

abstract class BaseAdminLog extends IPF_ORM_Record
{
  public static function setTableDefinition(IPF_ORM_Table $table)
  {
    $table->setTableName('admin_log');
    $table->setColumn('username', 'string', 32, array('type' => 'string', 'length' => '32'));
    $table->setColumn('user_id', 'integer', null, array('type' => 'integer'));
    $table->setColumn('object_id', 'integer', null, array('type' => 'integer'));
    $table->setColumn('object_class', 'string', 200, array('type' => 'string', 'length' => '200'));
    $table->setColumn('object_repr', 'string', 200, array('type' => 'string', 'length' => '200'));
    $table->setColumn('action_flag', 'integer', null, array('type' => 'integer'));
    $table->setColumn('change_message', 'string', 200, array('type' => 'string', 'length' => '200'));
    $table->addIndex('idx_object_id', array('fields' => 'object_id'));
    $table->addIndex('idx_object_class', array('fields' => 'object_class'));
    $table->addIndex('idx_created_at', array('fields' => 'created_at'));
    $table->addIndex('idx_action_flag', array('fields' => 'action_flag'));
    $table->setOption('type', 'INNODB');
    $table->setOption('collate', 'utf8_unicode_ci');
    $table->setOption('charset', 'utf8');

  }

  public static function setUp(IPF_ORM_Table $table)
  {
    $table->addTemplate(new IPF_ORM_Template_Timestampable(array('updated' => array('disabled' => true))));
  }

  public static function table()
  {
    return IPF_ORM::getTable('AdminLog');
  }

  public static function query($alias='')
  {
    return IPF_ORM::getTable('AdminLog')->createQuery($alias);
  }
}